### ISSUE TITLE
Bug when serializing JsonExtensionData of a class with a readonly property

### ISSUE THREAD

**Issue by arturenault** [JamesNK/Newtonsoft.Json#1907]
Hello,

Our service recently went down due to what we believe is a bug in Newtonsoft. We are using version 11.0.2. Here is what happened:

We have a class named NetworkState, which contains (among other things) a readonly property called HasIngressConfig, which looks like this:

```csharp
        public bool HasIngressConfig => this.IngressConfig != null;
```

We recently added a JsonExtensionData property called AdditionalData, which looks like this:
```csharp
        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, JToken> AdditionalData { get; set; } = new Dictionary<string, JToken>();
```

Upon deploying the change that adds the AdditionalData, the service started returning the following 500 error message:

```
Newtonsoft.Json.JsonSerializationException: Error setting value in extension data for type 'Microsoft.SeaBreeze.NetworkResourceManager.Model.Networks.NetworkProperties'. Path 'Properties.HasIngressConfig', line 1, position 2338. ---> System.ArgumentException: An item with the same key has already been added.\r\n   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at Void Add(System.String, Newtonsoft.Json.Linq.JToken)(Object , Object[] )\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)\r\n   --- End of inner exception stack trace ---\r\n   at System.Fabric.Store.TStore`5.<>c__DisplayClass329_0.<EnumerateComponentKeys>b__0(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ServiceFabric.Data.ReplicatedStore.DifferentialStore.KeyValueAsyncEnumerator`2.<MoveNextAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ServiceFabric.Data.Collections.SnapshotAsyncEnumerator`2.<MoveNextAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at System.Fabric.Wrp.ReliableDictionaryDataAccess.IAsyncEnumerableExtensions.<ForeachAsync>d__2`1.MoveNext() in D:\\SeaBreeze\\src\\Common\\ReliableDictionaryDataAccess\\IAsyncEnumerableExtensions.cs:line 68\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Fabric.Wrp.ReliableDictionaryDataAccess.PersistedStore`2.<GetReadOnlyEntriesAsync>d__14.MoveNext() in D:\\SeaBreeze\\src\\Common\\ReliableDictionaryDataAccess\\PersistedStore.cs:line 87\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.SeaBreeze.NetworkResourceManager.Operation.Networks.GetNetworksAdminOperation.<ExecuteAsync>d__14.MoveNext() in D:\\SeaBreeze\\src\\NetworkResourceManager\\Operation\\Networks\\GetNetworksAdminOperation.cs:line 84\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ServiceFabric.Rp.Operation.OperationBaseWithoutInstrumentation`1.<RunAsync>d__49.MoveNext()
```

Reverting the change seems to have fixed the issue for us. Here's what happened:

1. NetworkProperties is serialized, including all of its properties.
2. NetworkProperties is deserialized, and since the serializer can’t find a place to store HasIngressConfig that property gets put in the AdditionalData dictionary.
3. NetworkState is serialized again, and now HasIngressConfig is serialized twice—once from the readonly property and once from the AdditionalData dictionary.
4. On deserialization, the serializer tries to put both properties in the AdditionalData dictionary under the same name. This throws the exception.

I would have expected at least one of the following things to be true:
- Any type that's in my class definition shouldn't be added to the ExtensionData, even if it's readonly. Otherwise, it should at least fail silently or add just one of the extra properties.
- If having JsonExtensionData and readonly properties in the same class is not supported, it should be documented.

Let me know if I missed anything or if anything is unclear in my scenario.

**Comment by arturenault** [comment]
Just did a small test and confirmed the issue:

```csharp
            ResourceId networkResourceId = new ResourceId(
                Guid.NewGuid().ToString(),
                "testRG",
                ResourceConstants.ProviderNamespace(false),
                new Tuple<string, string>(ResourceConstants.NetworkResourceType, "testNetwork"));

            var newClass = new NetworkState(networkResourceId)
            {
                Properties = new NetworkProperties()
                {
                    Description = "test Network",
                    AddressPrefix = "128.42.0.0/24",
                    IngressConfig = new IngressConfig()
                    {
                        QosLevel = IngressQosLevel.Bronze,
                        Layer4 = new Layer4IngressConfig[1] {
                            new Layer4IngressConfig()
                            {
                                Name = "testIngressConfig",
                                ApplicationName = "testApplication",
                                ServiceName = "testService",
                                EndpointName = "testEndpoint",
                                PublicPort  = 45
                            }
                        },
                        PublicIPAddress = "128.42.0.0"
                    }
                }
            };

            var serializationSettings = WrpJsonSerializer.GetDefaultPublicSerializationSettings();
            serializationSettings.DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore;
            string newClassSerialized = WrpJsonSerializer.SerializeObjectToString(newClass, serializationSettings);
            Console.WriteLine(newClassSerialized);

            NetworkState oldClass = WrpJsonSerializer.DeserializeObjectFromString<NetworkState>
                (newClassSerialized, serializationSettings);
            string oldClassSerialized = WrpJsonSerializer.SerializeObjectToString(newClass, serializationSettings);
            Console.WriteLine(oldClassSerialized);

            NetworkState oldClassRoundTrip = WrpJsonSerializer.DeserializeObjectFromString<NetworkState>(oldClassSerialized, serializationSettings);
            string oldClassRoundTripSerialized = WrpJsonSerializer.SerializeObjectToString(oldClassRoundTrip, serializationSettings);
            Console.WriteLine(oldClassRoundTripSerialized);

            NetworkState roundTripNewClass = WrpJsonSerializer.DeserializeObjectFromString<NetworkState>
                (oldClassRoundTripSerialized, serializationSettings);

            Assert.AreEqual(
                WrpJsonSerializer.SerializeObjectToString(newClass, serializationSettings),
                WrpJsonSerializer.SerializeObjectToString(roundTripNewClass, serializationSettings));
```

This prints out:
```javascript
{
  "type": "Microsoft.ServiceFabricMesh/networks",
  "id": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "name": "testNetwork",
  "tags": {},
  "asyncOperations": {},
  "changedAsyncOperations": [],
  "properties": {
    "description": "test Network",
    "addressPrefix": "128.42.0.0/24",
    "ingressConfig": {
      "publicIPAddress": "128.42.0.0",
      "layer4": [
        {
          "name": "testIngressConfig",
          "publicPort": 45,
          "applicationName": "testApplication",
          "serviceName": "testService",
          "endpointName": "testEndpoint"
        }
      ]
    },
    "hasIngressConfig": true
  },
  "storeKey": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "referencingResourceIds": [],
  "dereferencedResourceIds": []
}
{
  "type": "Microsoft.ServiceFabricMesh/networks",
  "id": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "name": "testNetwork",
  "tags": {},
  "asyncOperations": {},
  "changedAsyncOperations": [],
  "properties": {
    "description": "test Network",
    "addressPrefix": "128.42.0.0/24",
    "ingressConfig": {
      "publicIPAddress": "128.42.0.0",
      "layer4": [
        {
          "name": "testIngressConfig",
          "publicPort": 45,
          "applicationName": "testApplication",
          "serviceName": "testService",
          "endpointName": "testEndpoint"
        }
      ]
    },
    "hasIngressConfig": true
  },
  "storeKey": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "referencingResourceIds": [],
  "dereferencedResourceIds": []
}
{
  "type": "Microsoft.ServiceFabricMesh/networks",
  "id": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "name": "testNetwork",
  "tags": {},
  "asyncOperations": {},
  "changedAsyncOperations": [],
  "properties": {
    "description": "test Network",
    "addressPrefix": "128.42.0.0/24",
    "ingressConfig": {
      "publicIPAddress": "128.42.0.0",
      "layer4": [
        {
          "name": "testIngressConfig",
          "publicPort": 45,
          "applicationName": "testApplication",
          "serviceName": "testService",
          "endpointName": "testEndpoint"
        }
      ]
    },
    "hasIngressConfig": true,
    "hasIngressConfig": true
  },
  "storeKey": "/subscriptions/77c04e11-f332-4543-b9da-07c13d06153d/resourcegroups/testRG/providers/Microsoft.ServiceFabricMesh/networks/testNetwork",
  "referencingResourceIds": [],
  "dereferencedResourceIds": []
}
```

As you can see, the third print has "hasIngressConfig" twice. Adding JsonIgnore to that property fixes the issue.

**Comment by JamesNK** [comment]
This is already fixed here - https://github.com/JamesNK/Newtonsoft.Json/issues/1719

**Comment by MiddleTommy** [comment]
v12.0.3 still has this problem. Readonly properties are getting written to extension data on deserializing and then extension data overwrites the readonly property in the json on serialization.

**Comment by trichling** [comment]
Hi, 

I can confirm it. The issue is still present. It duplicates read only properties in a second serialization:

```

public class SomeStructure
{
    public string Name { get; set; }

    public string NameFirstLetter => Name.First().ToString();

    [JsonExtensionData]
    public Dictionary<string, object> AdditionalData { get; set; }
}


[TestMethod]
public void DuplicateReadOnlyProperties()
{
    var structure = new SomeStructure()
    {
        Name = "Tobias"
    };

    var json = JsonConvert.SerializeObject(structure);

    var structureReloaded = JsonConvert.DeserializeObject<SomeStructure>(json);

    var json2 = JsonConvert.SerializeObject(structureReloaded);

    Assert.AreEqual(json, json2); // Fails
}


json: {"Name":"Tobias","NameFirstLetter":"T"}
json2: {"Name":"Tobias","NameFirstLetter":"T","NameFirstLetter":"T"}

``` 

Should this issue be re-opened or a newly one created?
