### ISSUE TITLE
Implicit conversion of bool to string throws exception

### ISSUE THREAD

**Issue by kobynet** [JamesNK/Newtonsoft.Json#775]
Running the following code 

```
private class Foo
{
    public string Test1 { get; set; }
}

public void run()
{
    JsonConvert.DeserializeObject<Foo>("{\"Test1\":false}");
}
```

works fine in version <= 7.0.1 while throwing Newtonsoft.Json.JsonReaderException in version = 8.0.1

**Comment by oxoocoffee** [comment]
I did encountered same bug after upgrading from 7.0.1 to 8.0.1. 

Here is JSON 

{
	“lc”:	[{
			"enable":	true,
			"nOut":	-109.642972
		}, {
			"enable":	false,
			"nOut":	-129.162981
		}]
}

Exception message is 

"Unexpected character encountered while processing value: t. Path 'lc[0].enable', line 3, position 14."

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/9021858293cd3b77b6ec5b9009b3fe9968c0470a

**Comment by JamesNK** [comment]
https://www.nuget.org/packages/Newtonsoft.Json/8.0.2

**Comment by AlexPhilippov** [comment]
Problem persist for dictionaries:
JsonConvert.DeserializeObject<Dictionary<string, string>>("{\"Test1\":false}");

**Comment by JamesNK** [comment]
Works for me:

```
[Test]
public void DeserializeBoolAsStringInDictionary()
{
    Dictionary<string, string> d = JsonConvert.DeserializeObject<Dictionary<string, string>>("{\"Test1\":false}");
    Assert.AreEqual(1, d.Count);
    Assert.AreEqual("false", d["Test1"]);
}
```

**Comment by AlexPhilippov** [comment]
Sorry, my mistake. All fine, seems like library got cached and I got wrong results.

**Comment by AlexPhilippov** [comment]
Boolean serialization used to start values with capital. Now it's not.
Following test running fine on 7.0.1, but failing on 8.0.2:
```
		[TestMethod]
		public void SerializeBool()
		{
			var obj = new { A = "A", B = true };
			var val = JsonConvert.SerializeObject(obj);
			var d = JsonConvert.DeserializeObject<Dictionary<string, string>>(val);
			Assert.AreEqual(2, d.Count);
			Assert.AreEqual("True", d["B"]);
		}
```
Not sure, if this related to this particular issue or separate one.

**Comment by Shockolate** [comment]
Deserializing JSON booleans as strings appear to be a "feature" of JSON.Net.
I'm viewing it as a bug; it is my understanding that  JSON booleans are not JSON strings.
Could you help me identify a setting to disable this feature? Or will I have to implement my own JsonConverter ?
@JamesNK

**Comment by rliberoff** [comment]
Is there a way to turn this off, so if the JSON sends a boolean value but the corresponding property is a string it throws an exception?
