### ISSUE TITLE
Exception in Partial Trust Environment

### ISSUE THREAD

**Issue by floyd-may** [JamesNK/Newtonsoft.Json#821]
I'm attempting to serialize F# union types in a Silverlight app. When I attempt this, I get an exception:

```
System.MethodAccessException occurred
  Message=Attempt by method 'System.Linq.Expressions.Expression.CreateLambda(System.Type, System.Linq.Expressions.Expression, System.String, Boolean, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>)' to access method 'System.Linq.Expressions.Expression`1<Newtonsoft.Json.Utilities.MethodCall`2<System.Object,System.Object>>.Create(System.Linq.Expressions.Expression, System.String, Boolean, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>)' failed.
  StackTrace:
       at System.RuntimeMethodHandle.PerformSecurityCheck(Object obj, RuntimeMethodHandleInternal method, RuntimeType parent, UInt32 invocationFlags)
       at System.RuntimeMethodHandle.PerformSecurityCheck(Object obj, IRuntimeMethodInfo method, RuntimeType parent, UInt32 invocationFlags)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Linq.Expressions.Expression.CreateLambda(Type delegateType, Expression body, String name, Boolean tailCall, ReadOnlyCollection`1 parameters)
       at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
       at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall[T](MethodBase method)
       at Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized(Assembly fsharpCoreAssembly)
       at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert(Type objectType)
       at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
```

From some brief code-surfing, I suspect the issue may be that the `BindingFlags` [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/FSharpUtils.cs#L91) include `BindingFlags.NonPublic`, which is a no-no in partial trust.

**Comment by floyd-may** [comment]
I'm working on a PR for fixing this now.

**Comment by JamesNK** [comment]
I believe I have fixed this here - https://github.com/JamesNK/Newtonsoft.Json/commit/eacb191f97cf460934d61d0a62ae8d3680c70528

**Comment by floyd-may** [comment]
Unfortunately that doesn't appear to fix the entire issue, but I'm not convinced that it **is** fixable. 

I updated to 8.0.3 and still get a `MethodAccessException` attempting to serialize anything FSharpy in my SIlverlight app. Apparently the way that the F# reflection API works, its attempt to sniff the `CompilationMappingAttribute` on F# types triggers the Silverlight runtime's security features.

I wrote a couple converters to work around it for serializing records and unions, but it makes some somewhat brittle assumptions.They will likely break horribly if you attempt to use them for stuff like `FSharpOption` or other built-in FSharpy stuff.

[here](https://gist.github.com/floyd-may/88941f7c6ff088614c70) is the record converter, and [here](https://gist.github.com/floyd-may/e4cc25f227899fff7ede) is the union converter. 

Both need to be instantiated per record or union type, which I handled by making a subclass of `DefaultContractResolver` and returning `JsonObjectContract`s with their `Converter` properties set to these converters. For instance:

```
private sealed class MyContractResolver : DefaultContractResolver
{
    public override JsonContract ResolveContract(Type type)
    {
        if (typeof(SomeUnionType).IsAssignableFrom(type))
        {
            var contract = new JsonObjectContract(typeof(object))
            {
                Converter = FSharpUnionConverter.Create<SomeUnionType>(x => x.Tag)
            };

            return contract;
        }

        if (new[] {
            typeof(SomeRecord),
            typeof(YetAnotherRecord),
            typeof(SurelyYouGetTheIdea)
        }.Contains(type))
        {
            return new JsonObjectContract(typeof(object))
            {
                Converter = new FSharpRecordConverter(type)
            };
        }

        return base.ResolveContract(type);
    }
}
```

Hope this helps somebody.
